### ISSUE TITLE
Edge.Cuts flatten Bezier issue

### ISSUE THREAD

**Issue by GuillermoTell** [badgeek/svg2shenzhen#103]
Hi, I don't know why, but I get this message:

Traceback (most recent call last):
  File "export.py", line 750, in <module>
    _main()
  File "export.py", line 746, in _main
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 123, in run
    self.save_raw(self.effect())
  File "export.py", line 323, in effect
    self.processExportLayer()
  File "export.py", line 468, in processExportLayer
    kicad_edgecut_string = self.exportEdgeCut(kicad_mod = options.filetype == "kicad_module")
  File "export.py", line 659, in exportEdgeCut
    y = (path[1][1])
IndexError: list index out of range

I'm using a simple rectangle as Edge.Cuts, already transformed into path. However, if I check the flatten Bezier option every time, it works.

**Comment by badgeek** [comment]
do you have example svg file ?

**Comment by GuillermoTell** [comment]
Here it is:
[Test.zip](https://github.com/badgeek/svg2shenzhen/files/5182608/Test.zip)

**Comment by iharshadec** [comment]
Here is your updated Test.zip. I am able to export properly.
1. I am not sure if you should do F.Mask-inverted you can leave F.Mask as it is.
2. You must do Prepare document first to make sure your drawing is within that area only.
3. You should add some more nodes to the path so lines are smooth when you see it on KiCad.

> if I check the flatten Bezier option every time, it works.

I have exported without using that flatten Bezier. Added more nodes. -- You can do that from **Extensions-->Modified Path-->Add Nodes...**

Here...

![image](https://user-images.githubusercontent.com/20681096/92431152-5f176f00-f1b4-11ea-8894-88f0b5abd554.png)

and then Apply

![image](https://user-images.githubusercontent.com/20681096/92431169-6e96b800-f1b4-11ea-9b2a-de53c3c079ae.png)



Here is your Test.zip.
[Test.zip](https://github.com/badgeek/svg2shenzhen/files/5185930/Test.zip)
