### ISSUE TITLE
Problem with EdgeCuts

### ISSUE THREAD

**Issue by oficinadesonido** [badgeek/svg2shenzhen#109]
Hello friends
thank you very much for all the work!

I am trying to use svg2shengzheng to make a panel of a musical instrument, and I have problems with the edge cut, I have seen some tutorials and I do not see any very difficult steps, but I get this error
(I use inkscape 1.01 and svg2shengzheng 0.2.18.7 in linux mint)

Traceback (most recent call last):
   File "export.py", line 750, in <module>
     _main ()
   File "export.py", line 746, in _main
     e.run ()
   File "/app/share/inkscape/extensions/inkex/base.py", line 140, in run
     self.save_raw (self.effect ())
   File "export.py", line 323, in effect
     self.processExportLayer ()
   File "export.py", line 430, in processExportLayer
     hash_sum = self.export_layers (layer_dest_svg_path, show_layer_ids)
   File "export.py", line 521, in export_layers
     root.remove (layer)
   File "src / lxml / etree.pyx", line 943, in lxml.etree._Element.remove
ValueError: Element is not a child of this node.

**Comment by vektorious** [comment]
Using Inkscape 1.01 and svg2shenzhen 0.2.18.7 (Linux Manjaro)

I got also got an error while exporting edge cuts (IndexError: list index out of range in edgecut export)

In my case the problem was that I converted my shape (rectangle with rounded edges) into a path and apparently this could not be converted by svg2shenzen. I then recreated the rectangle and did NOT convert it to path and the error disappeared.

EDIT: Forget what I wrote. It throws no error because it does not export the EdgeCuts ...
This is the error I'm getting

Traceback (most recent call last):
  File "export.py", line 750, in <module>
    _main()
  File "export.py", line 746, in _main
    e.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 140, in run
    self.save_raw(self.effect())
  File "export.py", line 323, in effect
    self.processExportLayer()
  File "export.py", line 468, in processExportLayer
    kicad_edgecut_string = self.exportEdgeCut(kicad_mod = options.filetype == "kicad_module")
  File "export.py", line 659, in exportEdgeCut
    y = (path[1][1])
IndexError: list index out of range
