### ISSUE TITLE
Error on export?

### ISSUE THREAD

**Issue by Bazmundi** [badgeek/svg2shenzhen#123]
Running InkScape:  1.0.2 (e86c870879, 2021-01-15, custom)
OS: Windoze 10
Downloaded [latest](https://github.com/badgeek/svg2shenzhen/releases/download/0.2.18.7/svg2shenzhen-extension-0.2.18.7.zip)

Followed destructions at: [https://github.com/badgeek/svg2shenzhen](https://github.com/badgeek/svg2shenzhen)

Got to export step and disappointedly received the following:

```
Traceback (most recent call last):
  File "export.py", line 750, in <module>
    _main()
  File "export.py", line 746, in _main
    e.run()
  File "C:\Program Files\WindowsApps\25415Inkscape.Inkscape_1.0.2.0_x64__9waqn51p1ttv2\VFS\ProgramFilesX64\Inkscape\share\inkscape\extensions\inkex\base.py", line 140, in run
    self.save_raw(self.effect())
  File "export.py", line 323, in effect
    self.processExportLayer()
  File "export.py", line 497, in processExportLayer
    with open(kicad_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Downloads\\ESPBee-master\\ESPBee-master\\Hardware\\EDA\\.svg2shenzhen-cache\\e46cda8ec6ee13898415c2dca0c9a784869ef2f0.pretty\\B.SilkS_g79.kicad_mod'
```

That is, literally only those steps to disappointment.

Went onto find it's straight forward to export PNG from InkScape and then suck it into KiCAD BMP to Component wizard.

Thanks for putting me onto InkScape.

**Comment by ghost** [comment]
Running InkScape: 1.0.2 (1.0.2+r75+1)
OS: Linux Mint 20.1
Downloaded latest

Not sure if this is the same problem or a different one, I get this on export (debug mode on):

```
inkscape -C -d 1200 -o "/home/rsholmes/Desktop/.svg2shenzhen-cache/images/B.Cu_g16.png" "/home/rsholmes/Desktop/.svg2shenzhen-cache/t347dc55.svg"
inkscape -C -d 1200 -o "/home/rsholmes/Desktop/.svg2shenzhen-cache/images/B.Mask_g18.png" "/home/rsholmes/Desktop/.svg2shenzhen-cache/1rvmb51o.svg"
inkscape -C -d 1200 -o "/home/rsholmes/Desktop/.svg2shenzhen-cache/images/B.SilkS_g20.png" "/home/rsholmes/Desktop/.svg2shenzhen-cache/8u17zx5p.svg"
inkscape -C -d 1200 -o "/home/rsholmes/Desktop/.svg2shenzhen-cache/images/F.Cu_g22.png" "/home/rsholmes/Desktop/.svg2shenzhen-cache/3e5gvyl0.svg"
inkscape -C -d 1200 -o "/home/rsholmes/Desktop/.svg2shenzhen-cache/images/F.Mask_g24.png" "/home/rsholmes/Desktop/.svg2shenzhen-cache/z3oaf_af.svg"
inkscape -C -d 1200 -o "/home/rsholmes/Desktop/.svg2shenzhen-cache/images/F.SilkS_g26.png" "/home/rsholmes/Desktop/.svg2shenzhen-cache/8yzg86v_.svg"
inkscape -C -d 1200 -o "/home/rsholmes/Desktop/.svg2shenzhen-cache/images/Dwgs.User_g28.png" "/home/rsholmes/Desktop/.svg2shenzhen-cache/vdc580fb.svg"
"/home/rsholmes/.config/inkscape/extensions/svg2shenzhen/bitmap2component_linux64" "/home/rsholmes/Desktop/.svg2shenzhen-cache/images/B.Cu_g16.png" "/home/rsholmes/Desktop/.svg2shenzhen-cache/foo.pretty/B.Cu_g16.kicad_mod" B.Cu true 1200 5
"/home/rsholmes/.config/inkscape/extensions/svg2shenzhen/bitmap2component_linux64" "/home/rsholmes/Desktop/.svg2shenzhen-cache/images/B.Mask_g18.png" "/home/rsholmes/Desktop/.svg2shenzhen-cache/foo.pretty/B.Mask_g18.kicad_mod" B.Mask true 1200 5
"/home/rsholmes/.config/inkscape/extensions/svg2shenzhen/bitmap2component_linux64" "/home/rsholmes/Desktop/.svg2shenzhen-cache/images/B.SilkS_g20.png" "/home/rsholmes/Desktop/.svg2shenzhen-cache/foo.pretty/B.SilkS_g20.kicad_mod" B.SilkS true 1200 5
"/home/rsholmes/.config/inkscape/extensions/svg2shenzhen/bitmap2component_linux64" "/home/rsholmes/Desktop/.svg2shenzhen-cache/images/F.Cu_g22.png" "/home/rsholmes/Desktop/.svg2shenzhen-cache/foo.pretty/F.Cu_g22.kicad_mod" F.Cu true 1200 5
"/home/rsholmes/.config/inkscape/extensions/svg2shenzhen/bitmap2component_linux64" "/home/rsholmes/Desktop/.svg2shenzhen-cache/images/F.Mask_g24.png" "/home/rsholmes/Desktop/.svg2shenzhen-cache/foo.pretty/F.Mask_g24.kicad_mod" F.Mask true 1200 5
"/home/rsholmes/.config/inkscape/extensions/svg2shenzhen/bitmap2component_linux64" "/home/rsholmes/Desktop/.svg2shenzhen-cache/images/F.SilkS_g26.png" "/home/rsholmes/Desktop/.svg2shenzhen-cache/foo.pretty/F.SilkS_g26.kicad_mod" F.SilkS true 1200 5
"/home/rsholmes/.config/inkscape/extensions/svg2shenzhen/bitmap2component_linux64" "/home/rsholmes/Desktop/.svg2shenzhen-cache/images/Dwgs.User_g28.png" "/home/rsholmes/Desktop/.svg2shenzhen-cache/foo.pretty/Dwgs.User_g28.kicad_mod" Dwgs.User true 1200 5
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "export.py", line 750, in <module>
    _main()
  File "export.py", line 746, in _main
    e.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 140, in run
    self.save_raw(self.effect())
  File "export.py", line 323, in effect
    self.processExportLayer()
  File "export.py", line 497, in processExportLayer
    with open(kicad_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rsholmes/Desktop/.svg2shenzhen-cache/foo.pretty/B.Cu_g16.kicad_mod'

```
In /home/rsholmes/Desktop/.svg2shenzhen-cache I find directory foo.pretty is empty.

I wanted to try checking whether the same happens in Inkscape 1.0. However it appears the only 1.0 download option available for Linux is AppImage, and when I tried that, I found it could not execute any extensions I tried without getting a fatal error. So, unfortunately, I cannot test this under Inkscape 1.0.
