### ISSUE TITLE
Export failure

### ISSUE THREAD

**Issue by endstreet** [badgeek/svg2shenzhen#127]
Traceback (most recent call last):
  File "export.py", line 750, in <module>
    _main()
  File "export.py", line 746, in _main
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 140, in run
    self.save_raw(self.effect())
  File "export.py", line 323, in effect
    self.processExportLayer()
  File "export.py", line 468, in processExportLayer
    kicad_edgecut_string = self.exportEdgeCut(kicad_mod = options.filetype == "kicad_module")
  File "export.py", line 659, in exportEdgeCut
    y = (path[1][1])
IndexError: list index out of range

[PouchConn.zip](https://github.com/badgeek/svg2shenzhen/files/6565920/PouchConn.zip)

I have uploaded the .SVG file.

**Comment by AEFeinstein** [comment]
I'm experiencing this as well
* Svg2Shenzhen 0.2.18.7
* Inkscape 1.0 (4035a4fb49, 2020-05-01)

**Comment by AEFeinstein** [comment]
The export works with Inkscape 1.1 (c68e22c387, 2021-05-23)
