### ISSUE TITLE
This just does not work.

### ISSUE THREAD

**Issue by kikendo** [badgeek/svg2shenzhen#140]
All I get is this error message:
`Traceback (most recent call last):
  File "export.py", line 3, in <module>
    import inkex
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\__init__.py", line 11, in <module>
    from .extensions import *
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\extensions.py", line 34, in <module>
    from .elements import (
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\elements\__init__.py", line 10, in <module>
    from ._base import ShapeElement, BaseElement
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\elements\_base.py", line 38, in <module>
    from ..styles import Style, Classes
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\styles.py", line 33, in <module>
    from .css import ConditionalRule
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\css.py", line 27, in <module>
    import cssselect
ModuleNotFoundError: No module named 'cssselect'
`

**Comment by pdlloyd** [comment]
It's a missing dependency error. Try `pip install cssselect`. See https://pypi.org/project/cssselect/ for more info
