### ISSUE TITLE
TypeError: expected a string or other character buffer object

### ISSUE THREAD

**Issue by beta-tester** [badgeek/svg2shenzhen#48]
hi, i tried to convert a SVG drawing to KiCAD from Inkscape 0.92, but i always get the following exception:
```
Traceback (most recent call last):
  File "export.py", line 740, in <module>
    _main()
  File "export.py", line 736, in _main
    e.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "export.py", line 313, in effect
    self.processExportLayer()
  File "export.py", line 463, in processExportLayer
    f.write(kicad_drill_string)
TypeError: expected a string or other character buffer object

```

i have no idea what is going on there...
hope you can help me.

i use Kubuntu 19.04:
`Linux my-pc 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`

the inkscape version from ubuntu repository:
`Inkscape 0.92.4 (5da689c313, 2019-01-14)
`

i extracted the extension to the following location:
```
my-pc:~/.config/inkscape/extensions$ tree .
.
├── svg2shenzhen
│   ├── bitmap2component.exe
│   ├── bitmap2component_linux64
│   ├── bitmap2component_osx
│   ├── export.py
│   └── prepare.py
├── svg2shenzhen_about.inx
├── svg2shenzhen_export.inx
└── svg2shenzhen_prepare.inx

```

the content of a simple inkscape file (only a red rectangle):
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="210mm"
   height="297mm"
   viewBox="0 0 210 297"
   version="1.1"
   id="svg8"
   inkscape:version="0.92.4 (5da689c313, 2019-01-14)"
   sodipodi:docname="drawing.svg">
  <defs
     id="defs2" />
  <sodipodi:namedview
     id="base"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageopacity="0.0"
     inkscape:pageshadow="2"
     inkscape:zoom="0.35"
     inkscape:cx="-505.71429"
     inkscape:cy="560"
     inkscape:document-units="mm"
     inkscape:current-layer="layer1"
     showgrid="false"
     inkscape:window-width="1920"
     inkscape:window-height="1135"
     inkscape:window-x="0"
     inkscape:window-y="0"
     inkscape:window-maximized="1" />
  <metadata
     id="metadata5">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     inkscape:label="Layer 1"
     inkscape:groupmode="layer"
     id="layer1">
    <rect
       style="opacity:1;fill:#ff0000;stroke:none;stroke-width:0.26458332"
       id="rect815"
       width="100"
       height="70"
       x="55"
       y="113.5" />
  </g>
</svg>

```

**Comment by beta-tester** [comment]
sorry, my fault...
i forgot to prepare the drawing, before exporting.
